name: branch-check

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: ['3.8', '3.9']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: checkout

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Dependencies
        run: pip install .

      - name: Test
        run: python setup.py coverage

      - name: Codacy
        if: github.event_name != 'pull_request'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
